import { categoryIcons } from "./icons";

export const emojiToKey: Record<string, string> = {
  "🍔": "food",
  "🍕": "food",
  "🍜": "food",
  "🍰": "food",
  "💰": "salary",
  "💵": "salary",
  "🤑": "salary",
  "💸": "expense",
  "🚗": "transport",
  "⛽": "transport",
  "🚌": "transport",
  "✈️": "travel",
  "✈": "travel",
  "🎉": "entertainment",
  "🎮": "entertainment",
  "🎬": "entertainment",
  "🎵": "entertainment",
  "💪": "health",
  "❤️": "health",
  "🩺": "health",
  "💊": "health",
  "🎓": "education",
  "📚": "education",
  "✏️": "education",
  "📖": "education",
  "🔌": "utilities",
  "💡": "utilities",
  "💧": "utilities",
  "⚡": "utilities",
  "🏠": "home",
  "🏡": "home",
  "💳": "credit_card",
  "🧾": "taxes",
  "📄": "taxes",
  "🛍️": "shopping",
  "🛒": "shopping",
  "👕": "shopping",
  "🎁": "gifts",
  "🏋️": "sports",
  "⚽": "sports",
  "🏀": "sports",
  "🏃": "sports",
  "🐾": "pets",
  "🐶": "pets",
  "🐱": "pets",
  "🔄": "subscriptions",
  "🔁": "subscriptions",
  "☕": "coffee",
  "📱": "electronics",
  "💻": "electronics",
  "🖥️": "electronics",
  "🧸": "kids",
  "👶": "kids",
  "💼": "business",
  "📈": "business",
  "📌": "other",
  "🔖": "other",
  "⭐": "other",
  "🙂": "other",
};

export function resolveIconKey(raw: string | undefined | null): string {
  if (!raw) return "other";
  if (raw in categoryIcons) return raw;
  if (raw in emojiToKey) return emojiToKey[raw];
  return "other";
}
