export type CategoryIconOption = {
  name: string;
  label: string;
};

export type CategoryIconGroup = {
  group: string;
  icons: CategoryIconOption[];
};

export const iconCatalog: CategoryIconGroup[] = [
  { group: "Еда и напитки", icons: [
    { name: "fork-knife", label: "Еда" },
    { name: "hamburger", label: "Бургер" },
    { name: "pizza", label: "Пицца" },
    { name: "coffee", label: "Кофе" },
    { name: "tea-bag", label: "Чай" },
    { name: "cake", label: "Торт" },
    { name: "cookie", label: "Печенье" },
    { name: "ice-cream", label: "Мороженое" },
    { name: "bread", label: "Хлеб" },
    { name: "carrot", label: "Овощи" },
    { name: "cherries", label: "Фрукты" },
    { name: "wine", label: "Вино" },
    { name: "beer-bottle", label: "Пиво" },
    { name: "bowl-food", label: "Тарелка" },
  ] },
  { group: "Транспорт", icons: [
    { name: "car", label: "Авто" },
    { name: "bus", label: "Автобус" },
    { name: "taxi", label: "Такси" },
    { name: "train", label: "Поезд" },
    { name: "airplane", label: "Самолёт" },
    { name: "bicycle", label: "Велосипед" },
    { name: "motorcycle", label: "Мотоцикл" },
    { name: "truck", label: "Грузовик" },
    { name: "gas-pump", label: "Топливо" },
    { name: "boat", label: "Лодка" },
    { name: "tram", label: "Трамвай" },
  ] },
  { group: "Дом и ЖКХ", icons: [
    { name: "house", label: "Дом" },
    { name: "house-line", label: "Жильё" },
    { name: "building-apartment", label: "Квартира" },
    { name: "building", label: "Здание" },
    { name: "key", label: "Ключ" },
    { name: "lightbulb", label: "Освещение" },
    { name: "lightning", label: "Электричество" },
    { name: "drop", label: "Вода" },
    { name: "wifi-high", label: "Интернет" },
    { name: "bed", label: "Кровать" },
    { name: "couch", label: "Диван" },
    { name: "washing-machine", label: "Стирка" },
  ] },
  { group: "Финансы", icons: [
    { name: "money", label: "Деньги" },
    { name: "wallet", label: "Кошелёк" },
    { name: "credit-card", label: "Карта" },
    { name: "bank", label: "Банк" },
    { name: "coins", label: "Монеты" },
    { name: "piggy-bank", label: "Копилка" },
    { name: "receipt", label: "Чек" },
    { name: "percent", label: "Процент" },
    { name: "chart-line-up", label: "Рост" },
    { name: "chart-line-down", label: "Спад" },
    { name: "chart-pie", label: "Диаграмма" },
    { name: "trend-up", label: "Доход" },
    { name: "trend-down", label: "Расход" },
    { name: "invoice", label: "Счёт" },
    { name: "arrows-clockwise", label: "Подписки" },
  ] },
  { group: "Покупки", icons: [
    { name: "shopping-cart", label: "Корзина" },
    { name: "shopping-bag", label: "Покупки" },
    { name: "gift", label: "Подарок" },
    { name: "package", label: "Посылка" },
    { name: "tag", label: "Ценник" },
    { name: "storefront", label: "Магазин" },
    { name: "tshirt", label: "Одежда" },
    { name: "sneaker", label: "Обувь" },
    { name: "basket", label: "Корзина" },
    { name: "handbag", label: "Сумка" },
  ] },
  { group: "Здоровье", icons: [
    { name: "heartbeat", label: "Здоровье" },
    { name: "first-aid-kit", label: "Аптечка" },
    { name: "pill", label: "Лекарства" },
    { name: "stethoscope", label: "Врач" },
    { name: "hospital", label: "Больница" },
    { name: "tooth", label: "Стоматолог" },
    { name: "heart", label: "Сердце" },
    { name: "brain", label: "Психолог" },
    { name: "bandaids", label: "Пластырь" },
    { name: "syringe", label: "Укол" },
  ] },
  { group: "Развлечения и спорт", icons: [
    { name: "game-controller", label: "Игры" },
    { name: "film-slate", label: "Кино" },
    { name: "music-notes", label: "Музыка" },
    { name: "headphones", label: "Наушники" },
    { name: "television", label: "ТВ" },
    { name: "book-open", label: "Книги" },
    { name: "ticket", label: "Билеты" },
    { name: "guitar", label: "Гитара" },
    { name: "puzzle-piece", label: "Хобби" },
    { name: "camera", label: "Фото" },
    { name: "basketball", label: "Баскетбол" },
    { name: "football", label: "Футбол" },
    { name: "tennis-ball", label: "Теннис" },
    { name: "trophy", label: "Победа" },
  ] },
  { group: "Образование", icons: [
    { name: "graduation-cap", label: "Образование" },
    { name: "books", label: "Учёба" },
    { name: "pencil", label: "Карандаш" },
    { name: "notebook", label: "Тетрадь" },
    { name: "chalkboard-teacher", label: "Уроки" },
    { name: "student", label: "Студент" },
    { name: "exam", label: "Экзамен" },
    { name: "pen", label: "Ручка" },
  ] },
  { group: "Работа и бизнес", icons: [
    { name: "briefcase", label: "Работа" },
    { name: "chart-bar", label: "Статистика" },
    { name: "chart-line", label: "График" },
    { name: "presentation-chart", label: "Презентация" },
    { name: "users", label: "Команда" },
    { name: "user", label: "Сотрудник" },
    { name: "handshake", label: "Сделка" },
    { name: "factory", label: "Производство" },
    { name: "hard-hat", label: "Стройка" },
    { name: "gear", label: "Настройки" },
  ] },
  { group: "Техника", icons: [
    { name: "device-mobile", label: "Телефон" },
    { name: "desktop", label: "Компьютер" },
    { name: "device-tablet", label: "Планшет" },
    { name: "laptop", label: "Ноутбук" },
    { name: "cpu", label: "Процессор" },
    { name: "printer", label: "Принтер" },
  ] },
  { group: "Путешествия", icons: [
    { name: "suitcase", label: "Чемодан" },
    { name: "map-pin", label: "Место" },
    { name: "compass", label: "Навигация" },
    { name: "island", label: "Отпуск" },
    { name: "tent", label: "Кемпинг" },
    { name: "mountains", label: "Горы" },
    { name: "sun", label: "Пляж" },
    { name: "globe", label: "Мир" },
  ] },
  { group: "Семья и питомцы", icons: [
    { name: "baby", label: "Дети" },
    { name: "users-three", label: "Семья" },
    { name: "paw-print", label: "Питомцы" },
    { name: "dog", label: "Собака" },
    { name: "cat", label: "Кошка" },
    { name: "heart-straight", label: "Любовь" },
    { name: "hand-heart", label: "Благотворительность" },
    { name: "users-four", label: "Компания" },
  ] },
  { group: "Прочее", icons: [
    { name: "dots-three-circle", label: "Другое" },
    { name: "star", label: "Избранное" },
    { name: "flag", label: "Флаг" },
    { name: "fire", label: "Срочно" },
    { name: "warning", label: "Внимание" },
    { name: "question", label: "Вопрос" },
    { name: "sparkle", label: "Блеск" },
    { name: "crown", label: "Премиум" },
    { name: "rocket", label: "Старт" },
    { name: "target", label: "Цель" },
  ] },
];
