import type { Icon } from "@phosphor-icons/react";
import { ForkKnifeIcon, HamburgerIcon, PizzaIcon, CoffeeIcon, TeaBagIcon, CakeIcon, CookieIcon, IceCreamIcon } from "@phosphor-icons/react";
import { BreadIcon, CarrotIcon, CherriesIcon, WineIcon, BeerBottleIcon, BowlFoodIcon, CarIcon, BusIcon } from "@phosphor-icons/react";
import { TaxiIcon, TrainIcon, AirplaneIcon, BicycleIcon, MotorcycleIcon, TruckIcon, GasPumpIcon, BoatIcon } from "@phosphor-icons/react";
import { TramIcon, HouseIcon, HouseLineIcon, BuildingApartmentIcon, BuildingIcon, KeyIcon, LightbulbIcon, LightningIcon } from "@phosphor-icons/react";
import { DropIcon, WifiHighIcon, BedIcon, CouchIcon, WashingMachineIcon, MoneyIcon, WalletIcon, CreditCardIcon } from "@phosphor-icons/react";
import { BankIcon, CoinsIcon, PiggyBankIcon, ReceiptIcon, PercentIcon, ChartLineUpIcon, ChartLineDownIcon, ChartPieIcon } from "@phosphor-icons/react";
import { TrendUpIcon, TrendDownIcon, InvoiceIcon, ArrowsClockwiseIcon, ShoppingCartIcon, ShoppingBagIcon, GiftIcon, PackageIcon } from "@phosphor-icons/react";
import { TagIcon, StorefrontIcon, TShirtIcon, SneakerIcon, BasketIcon, HandbagIcon, HeartbeatIcon, FirstAidKitIcon } from "@phosphor-icons/react";
import { PillIcon, StethoscopeIcon, HospitalIcon, ToothIcon, HeartIcon, BrainIcon, BandaidsIcon, SyringeIcon } from "@phosphor-icons/react";
import { GameControllerIcon, FilmSlateIcon, MusicNotesIcon, HeadphonesIcon, TelevisionIcon, BookOpenIcon, TicketIcon, GuitarIcon } from "@phosphor-icons/react";
import { PuzzlePieceIcon, CameraIcon, BasketballIcon, FootballIcon, TennisBallIcon, TrophyIcon, GraduationCapIcon, BooksIcon } from "@phosphor-icons/react";
import { PencilIcon, NotebookIcon, ChalkboardTeacherIcon, StudentIcon, ExamIcon, PenIcon, BriefcaseIcon, ChartBarIcon } from "@phosphor-icons/react";
import { ChartLineIcon, PresentationChartIcon, UsersIcon, UserIcon, HandshakeIcon, FactoryIcon, HardHatIcon, GearIcon } from "@phosphor-icons/react";
import { DeviceMobileIcon, DesktopIcon, DeviceTabletIcon, LaptopIcon, CpuIcon, PrinterIcon, SuitcaseIcon, MapPinIcon } from "@phosphor-icons/react";
import { CompassIcon, IslandIcon, TentIcon, MountainsIcon, SunIcon, GlobeIcon, BabyIcon, UsersThreeIcon } from "@phosphor-icons/react";
import { PawPrintIcon, DogIcon, CatIcon, HeartStraightIcon, HandHeartIcon, UsersFourIcon, DotsThreeCircleIcon, StarIcon } from "@phosphor-icons/react";
import { FlagIcon, FireIcon, WarningIcon, QuestionIcon, SparkleIcon, CrownIcon, RocketIcon, TargetIcon } from "@phosphor-icons/react";
import { PencilSimpleIcon, TrashIcon } from "@phosphor-icons/react";

export const categoryIcons: Record<string, Icon> = {
  "fork-knife": ForkKnifeIcon,
  "hamburger": HamburgerIcon,
  "pizza": PizzaIcon,
  "coffee": CoffeeIcon,
  "tea-bag": TeaBagIcon,
  "cake": CakeIcon,
  "cookie": CookieIcon,
  "ice-cream": IceCreamIcon,
  "bread": BreadIcon,
  "carrot": CarrotIcon,
  "cherries": CherriesIcon,
  "wine": WineIcon,
  "beer-bottle": BeerBottleIcon,
  "bowl-food": BowlFoodIcon,
  "car": CarIcon,
  "bus": BusIcon,
  "taxi": TaxiIcon,
  "train": TrainIcon,
  "airplane": AirplaneIcon,
  "bicycle": BicycleIcon,
  "motorcycle": MotorcycleIcon,
  "truck": TruckIcon,
  "gas-pump": GasPumpIcon,
  "boat": BoatIcon,
  "tram": TramIcon,
  "house": HouseIcon,
  "house-line": HouseLineIcon,
  "building-apartment": BuildingApartmentIcon,
  "building": BuildingIcon,
  "key": KeyIcon,
  "lightbulb": LightbulbIcon,
  "lightning": LightningIcon,
  "drop": DropIcon,
  "wifi-high": WifiHighIcon,
  "bed": BedIcon,
  "couch": CouchIcon,
  "washing-machine": WashingMachineIcon,
  "money": MoneyIcon,
  "wallet": WalletIcon,
  "credit-card": CreditCardIcon,
  "bank": BankIcon,
  "coins": CoinsIcon,
  "piggy-bank": PiggyBankIcon,
  "receipt": ReceiptIcon,
  "percent": PercentIcon,
  "chart-line-up": ChartLineUpIcon,
  "chart-line-down": ChartLineDownIcon,
  "chart-pie": ChartPieIcon,
  "trend-up": TrendUpIcon,
  "trend-down": TrendDownIcon,
  "invoice": InvoiceIcon,
  "arrows-clockwise": ArrowsClockwiseIcon,
  "shopping-cart": ShoppingCartIcon,
  "shopping-bag": ShoppingBagIcon,
  "gift": GiftIcon,
  "package": PackageIcon,
  "tag": TagIcon,
  "storefront": StorefrontIcon,
  "tshirt": TShirtIcon,
  "sneaker": SneakerIcon,
  "basket": BasketIcon,
  "handbag": HandbagIcon,
  "heartbeat": HeartbeatIcon,
  "first-aid-kit": FirstAidKitIcon,
  "pill": PillIcon,
  "stethoscope": StethoscopeIcon,
  "hospital": HospitalIcon,
  "tooth": ToothIcon,
  "heart": HeartIcon,
  "brain": BrainIcon,
  "bandaids": BandaidsIcon,
  "syringe": SyringeIcon,
  "game-controller": GameControllerIcon,
  "film-slate": FilmSlateIcon,
  "music-notes": MusicNotesIcon,
  "headphones": HeadphonesIcon,
  "television": TelevisionIcon,
  "book-open": BookOpenIcon,
  "ticket": TicketIcon,
  "guitar": GuitarIcon,
  "puzzle-piece": PuzzlePieceIcon,
  "camera": CameraIcon,
  "basketball": BasketballIcon,
  "football": FootballIcon,
  "tennis-ball": TennisBallIcon,
  "trophy": TrophyIcon,
  "graduation-cap": GraduationCapIcon,
  "books": BooksIcon,
  "pencil": PencilIcon,
  "notebook": NotebookIcon,
  "chalkboard-teacher": ChalkboardTeacherIcon,
  "student": StudentIcon,
  "exam": ExamIcon,
  "pen": PenIcon,
  "briefcase": BriefcaseIcon,
  "chart-bar": ChartBarIcon,
  "chart-line": ChartLineIcon,
  "presentation-chart": PresentationChartIcon,
  "users": UsersIcon,
  "user": UserIcon,
  "handshake": HandshakeIcon,
  "factory": FactoryIcon,
  "hard-hat": HardHatIcon,
  "gear": GearIcon,
  "device-mobile": DeviceMobileIcon,
  "desktop": DesktopIcon,
  "device-tablet": DeviceTabletIcon,
  "laptop": LaptopIcon,
  "cpu": CpuIcon,
  "printer": PrinterIcon,
  "suitcase": SuitcaseIcon,
  "map-pin": MapPinIcon,
  "compass": CompassIcon,
  "island": IslandIcon,
  "tent": TentIcon,
  "mountains": MountainsIcon,
  "sun": SunIcon,
  "globe": GlobeIcon,
  "baby": BabyIcon,
  "users-three": UsersThreeIcon,
  "paw-print": PawPrintIcon,
  "dog": DogIcon,
  "cat": CatIcon,
  "heart-straight": HeartStraightIcon,
  "hand-heart": HandHeartIcon,
  "users-four": UsersFourIcon,
  "dots-three-circle": DotsThreeCircleIcon,
  "star": StarIcon,
  "flag": FlagIcon,
  "fire": FireIcon,
  "warning": WarningIcon,
  "question": QuestionIcon,
  "sparkle": SparkleIcon,
  "crown": CrownIcon,
  "rocket": RocketIcon,
  "target": TargetIcon,
  "pencil-simple": PencilSimpleIcon,
  "trash": TrashIcon,
};
